### PR TITLE
Add recruitment

### PR DESCRIPTION
**Pull request by James-Thorson-NOAA**

### CODE REVIEW

**Comment by Johnausfisher** [comment]
Thanks Jim for all this brilliant work (in your spare time!).
Does Shiny output recruitment parameters - my connection with shiny doesn't.
Unfortunately my software-ignorance at this point gives me no capacity to run R routines.

**Comment by James-Thorson-NOAA** [comment]
Currently, the best way to access parameters is via installation in R, please see the main page for an example: https://github.com/James-Thorson-NOAA/FishLife .  In the future I hope to find a better way to host output long-term.

Feel free to email me if you'd like to discuss your use-case further.

**Comment by Johnausfisher** [comment]
Thanks Jim for your reply

 

I had help today installing a fresh R environment on my computer and the Fishlife package.

 

However we ran into trouble with the Error: 'fishbase' is not an exported object from 'namespace:rfishbase'.

 

I understand that you may be aware of this issue for users of Fishlife. Are you able to elaborate on the situation and advise if there is a work around for this problem that is practical for a novice like myself?

 

Best regards.

**Comment by James-Thorson-NOAA** [comment]
Do you mind re-posting the question under the Issues tab?  I don't think this comment thread on the most recent release will be easy to track.

**Pull request merged**
